version: '3'

services:
  dns-hospitalbinissalem:
    build:
      context: ..
      dockerfile: dhcp.Dockerfile
    container_name: dk-kea-DHCP-SERVER01
    ports:
      - 67:67/udp
      - 8000:8000/tcp
    volumes:
      - ./etc/kea:/etc/kea:rw

